# Generated by Django 4.2.7 on 2023-11-28 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyModel",
            new_name="ClassModel",
        ),
    ]
