# Generated by Django 4.2.7 on 2023-11-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_rename_mymodel_classmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
