# Generated by Django 4.2.7 on 2023-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_alter_classmodel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classmodel",
            name="age",
        ),
        migrations.RemoveField(
            model_name="classmodel",
            name="email",
        ),
        migrations.AddField(
            model_name="classmodel",
            name="class_motto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
