# Generated by Django 4.2.7 on 2023-12-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_studentmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "student_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.studentmodel",
                    ),
                ),
            ],
        ),
    ]
